---
name: Win32-CommandLine
version: 0.4.3.50
author:
  - 'Roy Ivy III <rivy[at]cpan[dot]org>'
abstract: Retrieve and reparse the Win32 command line
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp::Assert: 0
  File::Which: 0
  perl: 5.6.0
build_requires:
  ExtUtils::Manifest: 1.54
  File::Basename: 0
  File::Spec: 0
  File::Spec::Functions: 0
  File::Which: 0
  Test::Differences: 0
  perl: 5.6.0
  version: 0
recommends:
  Win32: 0
  Win32::API: 0
  Win32::Security::SID: 0
  Win32::TieRegistry: 0
provides:
  Win32::CommandLine:
    file: lib/Win32/CommandLine.pm
    version: 0.4.3.50
generated_by: Module::Build version 0.31012
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
